# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mD-caXZEwJbjMjcUxLAEEXRO8kJ0SF8Q
"""



#Numpy Creation of 3x5
import numpy as np
m=np.random.randint(1,20,15)
print(m)

#reshape the array
n=m.reshape((3,5))
print(n)

#print shape of array
print(n.shape)

#replace max in each row by 0
np.max(n,axis=1)
#print(len(n))
for i in n:
  #print(i)
  o=i.max()
  #print(o)
  for j in range(len(i)):
    if i[j]==0:
      #print(i[j])
      i[j]=0
      #print(i[j])
print(n)





# creation of two-dimentional array of size 4x3
a=np.array([[1,7,9],[9,5,7],[10,6,5],[14,23,3]],np.int32)
print(type(a),a.shape,a.dtype)

#calculate eigen values and Right eigen vector
ar=np.array([[3,-2],[1,0]])
print(ar)
e,v=np.linalg.eig(ar)
print("Eigen value:\n", e)
print("Right eigen vector :\n", v)

#sum of diagonal elements
arr=np.array([[0,1,2],[3,4,5]])
print(arr)
sum=np.trace(arr)
print(sum)

#reshape the given data
arr1=np.arange(1,7)
print(arr1)
arr1=arr1.reshape((3,2))
print(arr1)
arr1=arr1.reshape((2,3))
print(arr1)



# Commented out IPython magic to ensure Python compatibility.
#matplotlib
# %matplotlib inline


from matplotlib import pyplot as pt


# available styles
pt.style.available


['Solarize_Light2',
'_classic_test_patch',
'_mpl-gallery',
'_mpl-gallery-nogrid',
'bmh', 'classic',
'dark_background',
'fast',
'fivethirtyeight',
'ggplot',
'grayscale',
'seaborn-v0_8',
'seaborn-v0_8-bright',
'seaborn-v0_8-colorblind',
'seaborn-v0_8-dark',
'seaborn-v0_8-dark-palette',
'seaborn-v0_8-darkgrid',
'seaborn-v0_8-deep',
'seaborn-v0_8-muted',
'seaborn-v0_8-notebook',
'seaborn-v0_8-paper',
'seaborn-v0_8-pastel',
'seaborn-v0_8-poster',
'seaborn-v0_8-talk',
'seaborn-v0_8-ticks',
'seaborn-v0_8-white',
'seaborn-v0_8-whitegrid',
'tableau-colorblind10']

pt.style.use("grayscale")

#sample data
#programming languages
prog=['Java', ' Python', 'PHP', 'JavaScript', 'C#','C++']
#popularity
po=[22.2, 17.6, 8.8, 8, 7.7, 6.7]
#colours
colour=['orange','green','blue','red','cyan','indigo']
explode=[0.2,0,0,0,0,0]

pt.pie(x=po,labels=prog,explode=explode,wedgeprops={'edgecolor':'black'},shadow=True,autopct='%1.1f%%',colors=colour)
pt.tight_layout()
pt.title("Popularity of Programming Languages")
pt.show()

